language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: leixia81-github
    token:
      secure: 2c12e5d314fd8b56ced00d81899afd3d6df4a254
jdk:
  - oraclejdk11
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'