language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: leixia81-github
    token:
      secure: 32fa0ed5164392dd10dc5201823ff26ee22a72da
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'