language: java
sudo: false
install: true
jdk:
  - oraclejdk11

addons:
  sonarcloud:
    organization: leixia81-github
    token:
      secure: 2c12e5d314fd8b56ced00d81899afd3d6df4a254   # this token should be encrypted

jobs:
  include:
    - verify:
      script:
        - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

stages:
  - verify

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'