spring:
  main:
    banner-mode: "off"
  profiles:
    active: test

---
spring:
  profiles: test
  data:
    mongodb:
      host: localhost
      port: 27017
      database: nullbeans
      username: myusername
      password: mypassword